[server]
port = 8075

#----------------
# Insert a # before each of the following 3 lines to make your application accessible in your home network
[browser]
serverAddress = "localhost"
port = 8075
#-------------

[client]
showErrorDetails = true

[theme]
primaryColor="#38bcf0"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#f2f2f7"
textColor="#262730"
font="sans serif"

[global]
